insert into materia(materia_ID, nombre, estado, grado) values (01,'Espanol 1', 'A', '1ro')
insert into materia(materia_ID, nombre, estado, grado) values (02,'Matematicas 1', 'A', '1ro')
insert into materia(materia_ID, nombre, estado, grado) values (03,'Ciencias Naturales 1', 'A', '1ro')
insert into materia(materia_ID, nombre, estado, grado) values (04,'Geografia 1', 'A', '1ro')
insert into materia(materia_ID, nombre, estado, grado) values (05,'Historia 1', 'A', '1ro')
insert into materia(materia_ID, nombre, estado, grado) values (06,'Formacion Civica y Etica 1', 'A', '1ro')
insert into materia(materia_ID, nombre, estado, grado) values (07,'Educacion Fisica 1', 'A', '1ro')
insert into materia(materia_ID, nombre, estado, grado) values (08,'Ingles', 'A', '1ro')
insert into materia(materia_ID, nombre, estado, grado) values (09,'Artes Plasticas', 'A','2do')
insert into materia(materia_ID, nombre, estado, grado) values (11,'Espanol 2', 'A','2do')
insert into materia(materia_ID, nombre, estado, grado) values (12,'Matematicas 2', 'A','2do')
insert into materia(materia_ID, nombre, estado, grado) values (13,'Ciencias Naturales 2', 'A','2do')
insert into materia(materia_ID, nombre, estado, grado) values (14,'Geografia 2', 'A','2do')
insert into materia(materia_ID, nombre, estado, grado) values (15,'Historia 2', 'A','2do')
insert into materia(materia_ID, nombre, estado, grado) values (16,'Formacion Civica y Etica 2', 'A','2do')
insert into materia(materia_ID, nombre, estado, grado) values (17,'Educacion Fisica 2', 'A','2do')
insert into materia(materia_ID, nombre, estado, grado) values (18,'Ingles 2', 'A','2do')
insert into materia(materia_ID, nombre, estado, grado) values (19,'Artes Plasticas 2', 'A','2do')
insert into materia(materia_ID, nombre, estado, grado) values (21,'Espanol 3', 'A','3ro')
insert into materia(materia_ID, nombre, estado, grado) values (22,'Matematicas 3', 'A','3ro')
insert into materia(materia_ID, nombre, estado, grado) values (23,'Ciencias Naturales 3', 'A','3ro')
insert into materia(materia_ID, nombre, estado, grado) values (24,'Geografia 3', 'A','3ro')
insert into materia(materia_ID, nombre, estado, grado) values (25,'Historia 3', 'A','3ro')
insert into materia(materia_ID, nombre, estado, grado) values (26,'Formacion Civica y Etica 3', 'A','3ro')
insert into materia(materia_ID, nombre, estado, grado) values (27,'Educacion Fisica 3', 'A','3ro')
insert into materia(materia_ID, nombre, estado, grado) values (28,'Ingles 3', 'A','3ro')
insert into materia(materia_ID, nombre, estado, grado) values (29,'Artes Plasticas 3', 'A','3ro')
insert into materia(materia_ID, nombre, estado, grado) values (31,'Espanol 4', 'A','4to')
insert into materia(materia_ID, nombre, estado, grado) values (32,'Matematicas 4', 'A','4to')
insert into materia(materia_ID, nombre, estado, grado) values (33,'Ciencias Naturales 4', 'A','4to')
insert into materia(materia_ID, nombre, estado, grado) values (34,'Geografia 4', 'A','4to')
insert into materia(materia_ID, nombre, estado, grado) values (35,'Historia 4', 'A','4to')
insert into materia(materia_ID, nombre, estado, grado) values (36,'Formacion Civica y Etica 4', 'A','4to')
insert into materia(materia_ID, nombre, estado, grado) values (37,'Educacion Fisica 4', 'A','4to')
insert into materia(materia_ID, nombre, estado, grado) values (38,'Ingles 4', 'A','4to')
insert into materia(materia_ID, nombre, estado, grado) values (39,'Artes Plasticas 4', 'A','4to')
insert into materia(materia_ID, nombre, estado, grado) values (41,'Espanol 5', 'A','5to')
insert into materia(materia_ID, nombre, estado, grado) values (42,'Matematicas 5', 'A','5to')
insert into materia(materia_ID, nombre, estado, grado) values (43,'Ciencias Naturales 5', 'A','5to')
insert into materia(materia_ID, nombre, estado, grado) values (44,'Geografia 5', 'A','5to')
insert into materia(materia_ID, nombre, estado, grado) values (45,'Historia 5', 'A','5to')
insert into materia(materia_ID, nombre, estado, grado) values (46,'Formacion Civica y Etica 5', 'A','5to')
insert into materia(materia_ID, nombre, estado, grado) values (47,'Educacion Fisica 5', 'A','5to')
insert into materia(materia_ID, nombre, estado, grado) values (48,'Ingles 5', 'A','5to')
insert into materia(materia_ID, nombre, estado, grado) values (49,'Artes Plasticas 5', 'A','5to')
insert into materia(materia_ID, nombre, estado, grado) values (51,'Espanol 6', 'A','6to')
insert into materia(materia_ID, nombre, estado, grado) values (52,'Matematicas 6', 'A','6to')
insert into materia(materia_ID, nombre, estado, grado) values (53,'Ciencias Naturales 6', 'A','6to')
insert into materia(materia_ID, nombre, estado, grado) values (54,'Geografia 6', 'A','6to')
insert into materia(materia_ID, nombre, estado, grado) values (55,'Historia 6', 'A','6to')
insert into materia(materia_ID, nombre, estado, grado) values (56,'Formacion Civica y Etica 6', 'A','6to')
insert into materia(materia_ID, nombre, estado, grado) values (57,'Educacion Fisica 6', 'A','6to')
insert into materia(materia_ID, nombre, estado, grado) values (58,'Ingles 6', 'A','6to')
insert into materia(materia_ID, nombre, estado, grado) values (59,'Artes Plasticas 6', 'A','6to')