insert into materia(materia_ID, nombre, estado) values (01,'Espanol 1', 'A')
insert into materia(materia_ID, nombre, estado) values (02,'Matematicas 1', 'A')
insert into materia(materia_ID, nombre, estado) values (03,'Ciencias Naturales 1', 'A')
insert into materia(materia_ID, nombre, estado) values (04,'Geografia 1', 'A')
insert into materia(materia_ID, nombre, estado) values (05,'Historia 1', 'A')
insert into materia(materia_ID, nombre, estado) values (06,'Formacion Civica y Etica 1', 'A')
insert into materia(materia_ID, nombre, estado) values (07,'Educacion Fisica 1', 'A')
insert into materia(materia_ID, nombre, estado) values (08,'Ingles', 'A')
insert into materia(materia_ID, nombre, estado) values (09,'Artes Plasticas', 'A')
insert into materia(materia_ID, nombre, estado) values (11,'Espanol 2', 'A')
insert into materia(materia_ID, nombre, estado) values (12,'Matematicas 2', 'A')
insert into materia(materia_ID, nombre, estado) values (13,'Ciencias Naturales 2', 'A')
insert into materia(materia_ID, nombre, estado) values (14,'Geografia 2', 'A')
insert into materia(materia_ID, nombre, estado) values (15,'Historia 2', 'A')
insert into materia(materia_ID, nombre, estado) values (16,'Formacion Civica y Etica 2', 'A')
insert into materia(materia_ID, nombre, estado) values (17,'Educacion Fisica 2', 'A')
insert into materia(materia_ID, nombre, estado) values (18,'Ingles 2', 'A')
insert into materia(materia_ID, nombre, estado) values (19,'Artes Plasticas 2', 'A')
insert into materia(materia_ID, nombre, estado) values (31,'Espanol 3', 'A')
insert into materia(materia_ID, nombre, estado) values (32,'Matematicas 3', 'A')
insert into materia(materia_ID, nombre, estado) values (33,'Ciencias Naturales 3', 'A')
insert into materia(materia_ID, nombre, estado) values (34,'Geografia 3', 'A')
insert into materia(materia_ID, nombre, estado) values (35,'Historia 3', 'A')
insert into materia(materia_ID, nombre, estado) values (36,'Formacion Civica y Etica 3', 'A')
insert into materia(materia_ID, nombre, estado) values (37,'Educacion Fisica 3', 'A')
insert into materia(materia_ID, nombre, estado) values (38,'Ingles 3', 'A')
insert into materia(materia_ID, nombre, estado) values (39,'Artes Plasticas 3', 'A')
insert into materia(materia_ID, nombre, estado) values (41,'Espanol 4', 'A')
insert into materia(materia_ID, nombre, estado) values (42,'Matematicas 4', 'A')
insert into materia(materia_ID, nombre, estado) values (43,'Ciencias Naturales 4', 'A')
insert into materia(materia_ID, nombre, estado) values (44,'Geografia 4', 'A')
insert into materia(materia_ID, nombre, estado) values (45,'Historia 4', 'A')
insert into materia(materia_ID, nombre, estado) values (46,'Formacion Civica y Etica 4', 'A')
insert into materia(materia_ID, nombre, estado) values (47,'Educacion Fisica 4', 'A')
insert into materia(materia_ID, nombre, estado) values (48,'Ingles 4', 'A')
insert into materia(materia_ID, nombre, estado) values (49,'Artes Plasticas 4', 'A')
insert into materia(materia_ID, nombre, estado) values (51,'Espanol 5', 'A')
insert into materia(materia_ID, nombre, estado) values (52,'Matematicas 5', 'A')
insert into materia(materia_ID, nombre, estado) values (53,'Ciencias Naturales 5', 'A')
insert into materia(materia_ID, nombre, estado) values (54,'Geografia 5', 'A')
insert into materia(materia_ID, nombre, estado) values (55,'Historia 5', 'A')
insert into materia(materia_ID, nombre, estado) values (56,'Formacion Civica y Etica 5', 'A')
insert into materia(materia_ID, nombre, estado) values (57,'Educacion Fisica 5', 'A')
insert into materia(materia_ID, nombre, estado) values (58,'Ingles 5', 'A')
insert into materia(materia_ID, nombre, estado) values (59,'Artes Plasticas 5', 'A')
insert into materia(materia_ID, nombre, estado) values (61,'Espanol 6', 'A')
insert into materia(materia_ID, nombre, estado) values (62,'Matematicas 6', 'A')
insert into materia(materia_ID, nombre, estado) values (63,'Ciencias Naturales 6', 'A')
insert into materia(materia_ID, nombre, estado) values (64,'Geografia 6', 'A')
insert into materia(materia_ID, nombre, estado) values (65,'Historia 6', 'A')
insert into materia(materia_ID, nombre, estado) values (66,'Formacion Civica y Etica 6', 'A')
insert into materia(materia_ID, nombre, estado) values (67,'Educacion Fisica 6', 'A')
insert into materia(materia_ID, nombre, estado) values (68,'Ingles 6', 'A')
insert into materia(materia_ID, nombre, estado) values (69,'Artes Plasticas 6', 'A')
